# Generated by Django 5.1 on 2025-09-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhouse',
            name='bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus accrual percent applied to booking final price (e.g., 5.00 for 5%).', max_digits=5),
        ),
    ]
