# Generated by Django 5.2.4 on 2025-07-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bathhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='users.bathhouse')),
            ],
            options={
                'unique_together': {('bathhouse', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('capacity', models.PositiveIntegerField(default=1)),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('has_pool', models.BooleanField(default=False)),
                ('bathhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='users.bathhouse')),
            ],
            options={
                'unique_together': {('bathhouse', 'room_number')},
            },
        ),
    ]
