# Generated by Django 5.1 on 2025-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bathhouse_bonus_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhouse',
            name='birthday_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Discount percent if it is the customer's birthday (e.g., 10.00).", max_digits=5),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='bonus_hour_days',
            field=models.JSONField(blank=True, default=list, help_text="Array of weekdays when Bonus Hour is valid, e.g., ['MONDAY','TUESDAY']."),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='bonus_hours_awarded',
            field=models.PositiveIntegerField(default=0, help_text='Number of free hours awarded when Bonus Hour applies.'),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='bonus_threshold_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='If final bill >= this amount, apply higher bonus percentage; otherwise lower.', max_digits=10),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='happy_hours_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percent during Happy Hours (e.g., 30.00).', max_digits=5),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='happy_hours_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='happy_hours_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='higher_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus percent for bills at or above the threshold.', max_digits=5),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='lower_bonus_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Bonus percent for bills below the threshold.', max_digits=5),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='min_hours_for_bonus',
            field=models.PositiveIntegerField(default=0, help_text='Minimum booking hours required to activate Bonus Hour.'),
        ),
    ]
