# Generated by Django 5.1 on 2025-09-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_bathhouse_birthday_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhouse',
            name='happy_hours_days',
            field=models.JSONField(blank=True, default=list, help_text="Array of weekdays when Happy Hours is valid, e.g., ['MONDAY','TUESDAY']."),
        ),
    ]
