# Generated by Django 5.2.4 on 2025-07-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_extraitem_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhouse',
            name='end_of_work',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='is_24_hours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='start_of_work',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
