# Generated by Django 5.1 on 2025-09-10 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bathhouse_happy_hours_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhouse',
            name='birthday_discount_enabled',
            field=models.BooleanField(default=False, help_text='Enable Birthday discount promotion'),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='bonus_accrual_enabled',
            field=models.BooleanField(default=True, help_text='Enable bonus accrual for this bathhouse'),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='bonus_hour_enabled',
            field=models.BooleanField(default=False, help_text='Enable Bonus Hour promotion'),
        ),
        migrations.AddField(
            model_name='bathhouse',
            name='happy_hours_enabled',
            field=models.BooleanField(default=False, help_text='Enable Happy Hours promotion'),
        ),
    ]
