# Generated by Django 5.2.4 on 2025-07-04 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_bathhouse_end_of_work_bathhouse_is_24_hours_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extraitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='extraitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='BathhouseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bathhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='users.bathhouse')),
            ],
            options={
                'unique_together': {('bathhouse', 'name')},
            },
        ),
        migrations.AddField(
            model_name='extraitem',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='users.bathhouseitem'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='extraitem',
            name='bathhouse',
        ),
        migrations.RemoveField(
            model_name='extraitem',
            name='description',
        ),
        migrations.RemoveField(
            model_name='extraitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='extraitem',
            name='price',
        ),
    ]
