# Generated by Django 5.1 on 2025-09-10 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_bathhouse_birthday_discount_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathhouse',
            name='bonus_percentage',
        ),
    ]
