# Generated by Django 5.2.4 on 2025-07-04 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_extra_items'),
        ('users', '0005_alter_extraitem_unique_together_extraitem_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extraitem',
            name='booking',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='extra_items', to='bookings.booking'),
            preserve_default=False,
        ),
    ]
