# Generated by Django 5.1 on 2025-07-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bathhouse_owner'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='room',
            name='has_recreation_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_steam_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_washing_area',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='heated_by_coal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='heated_by_wood',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='holiday_price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='room',
            name='is_bathhouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='is_sauna',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together={('bathhouse', 'room_number', 'is_bathhouse', 'is_sauna')},
        ),
    ]
