# Generated by Django 5.1 on 2025-07-16 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_room_unique_together_room_has_recreation_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
