# Generated by Django 5.1 on 2025-07-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_room_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bathhouseitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bathhouse_items/'),
        ),
        migrations.AddField(
            model_name='bathhouseitem',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
