# Generated by Django 5.1 on 2025-07-16 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_bathhouseitem_image_bathhouseitem_is_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bathhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='users.bathhouse')),
            ],
        ),
        migrations.AddField(
            model_name='bathhouseitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='users.menucategory'),
        ),
    ]
