# Generated by Django 5.2.4 on 2025-07-04 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_extraitem_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('hours', models.PositiveIntegerField(default=1)),
                ('confirmed', models.BooleanField(default=False)),
                ('sms_code', models.CharField(blank=True, max_length=10, null=True)),
                ('bathhouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.bathhouse')),
                ('extra_items', models.ManyToManyField(blank=True, related_name='bookings', to='users.extraitem')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.room')),
            ],
        ),
    ]
