# Generated by Django 5.2.4 on 2025-09-05 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('hours', models.PositiveIntegerField(default=1)),
                ('confirmed', models.BooleanField(default=True)),
                ('sms_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, help_text='The final calculated price at the time of booking creation', max_digits=10, null=True)),
            ],
        ),
    ]
