# Generated by Django 5.2.4 on 2025-07-04 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='extra_items',
        ),
    ]
