# Generated by Django 5.1 on 2025-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bonusaccount_bonustransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Whether the booking has been paid'),
        ),
    ]
