# Generated by Django 5.1 on 2025-09-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_birthday',
            field=models.BooleanField(default=False, help_text='Customer confirmed birthday'),
        ),
    ]
