# Generated by Django 5.1 on 2025-09-05 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_booking_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The final calculated price at the time of booking creation', max_digits=10, null=True),
        ),
    ]
